### PR TITLE
Check project directories

### PR DESCRIPTION
**Pull request by rafaelDev0ps**
this pull request is related to the issue #2 
1. check if the project directory matches with project name
```go
func HasModuleFile(path string) bool {
	_, err := os.Stat(path)
	return !os.IsNotExist(err)
}

func CheckProjectDirectories(path string) error {
	pagesPath := filepath.Join(path, "pages")
	_, err := os.Stat(pagesPath)
	if err != nil {
		return fmt.Errorf("The directory pages does not exist.")
	}

	partialsPath := filepath.Join(path, "partials")
	_, err = os.Stat(partialsPath)
	if err != nil {
		return fmt.Errorf("The directory partials does not exist.")
	}

	return nil
}
```
2. make sure go.mod file of the project created exists
```go
if HasModuleFile(modPath) == false {
	fmt.Fprintf(os.Stderr, "Module not found: go.mod file does not exist.")
	return ""
}

checkDir := CheckProjectDirectories(wd)
if checkDir != nil {
	fmt.Fprintf(os.Stderr, checkDir.Error())
	return ""
}
```

### CODE REVIEW

**Comment by rafaelDev0ps** [comment]
hey @maddalax do you intend to merge this PR?

**Comment by maddalax** [comment]
> hey @maddalax do you intend to merge this PR?

yes sorry, will soon

**Comment by rafaelDev0ps** [comment]
Sure, I'll update soon

**Comment by rafaelDev0ps** [comment]
@maddalax done ✅

**Pull request merged**
